blank_issues_enabled: false
contact_links:
  - name: Tổ Sư Thiền 1
    url: https://youtube.com/
    about: ...
  - name: Tổ Sư Thiền 2
    url: https://youtube.com/
    about: ...
  - name: Tổ Sư Thiền 3
    url: https://youtube.com/
    about: ...
